apiVersion: v1
kind: Secret
metadata:
  name: fast-food-api-secret
  labels:
    app: fast-food-api-secret
type: Opaque
stringData:
  # TODO: Replace Tokens
  ConnectionStrings__Default: "Server=fast-food-database-service;Database=postgres;Username=postgres;Password=docker;Port=5432"
